namespace AIOneWinUI
{
    [default_interface]
    runtimeclass BlankUserControl : Microsoft.UI.Xaml.Controls.UserControl, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        BlankUserControl();
        Int32 MyProperty;
        String Text { get; };
    }
}
