import "BlankUserControl.idl";

namespace AIOneWinUI
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        Windows.Foundation.Collections.IObservableVector<BlankUserControl> Messages{ get; };
    }
}
