import "BlankUserControl.idl";

namespace AIOneWinUI
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Int32 MyProperty;
        Windows.Foundation.Collections.IObservableVector<BlankUserControl> Messages{ get; };
    }
}
