import "MessageControl.idl";

namespace AIOneWinUI
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Windows.Foundation.Collections.IObservableVector<MessageControl> Messages{ get; };
    }
}
