namespace AIOneWinUI
{
    [default_interface]
    [Microsoft.UI.Xaml.Data.Bindable]
    runtimeclass MessageControl : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MessageControl();
        String Role;
        String Text;
    }
}
